config/routes.rb
Candv::Application.routes.draw do
resources :users
resources :posts
resources :products

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :products
  attr_accessible :name, :category_id
  validates :name, :presence => true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  category_id :integer
#  description :text
#  pricing     :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  belongs_to :category
  attr_accessible :description, :name, :pricing, :category_id
  validates :category, :description, :name, :pricing, :presence => true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  email_address :string(255)
#  password      :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email_address, :first_name, :last_name, :password
  validates :first_name, :last_name, :email_address, :password, :presence => true

  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

  end

  def show
    @products = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      flash[:success] = "Product Added"
      redirect_to products_path

    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      flash[:success] = "Success: Product Updated!"
      redirect_to @product

    else
      render 'edit'
      
    end
  end

  def destroy
    @products = Product.find(params[:id])
    @products.destroy

    flash[:danger] = "Product Deleted"
    redirect_to products_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all

  end

  def show
  	@user = User.find(params[:id])

  end

  def new
  	@user = User.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(params[:user])

  		if @user.save
  			flash[:success] = "Success: New User Created!"
  			redirect_to users_path
  	
  		else render 'new'
		end
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(params[:user])
			flash[:success] = "User Profile Updated!"
			redirect_to @user

		else render 'edit'
		end
	end

	def destroy 
		@user = User.find(params[:id])
		@user.destroy

		flash[:danger] = "Account Deleted!"
		redirect_to users_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Candv</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "posts", :media => "all" %>
  <%= javascript_include_tag "posts.js.coffee" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "products", :media => "all" %>
  <%= javascript_include_tag "products.js.coffee" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "users", :media => "all" %>
  <%= javascript_include_tag "users.js.coffee" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% content_for :title do %>Display All Posts<% end %>
<div class="hero-unit">
	<h1>Where We Post!</h1>
</div>

app/views/posts/new.html.erb
<% content_for :title do %>Add a new post<% end %><div class="container">
	<div class="form-horizontal">
		<form id="new_user" action="/users/new" method="post">
			<div class="control-group">
				<h1>Add a Post!</h1>
				<div class="control-label">
					<label for="user_name">Name: </label>
				</div>
				<div class="controls">
					<input type="text" name="user['name']" />
				</div>
			</div>
			<div class="control-group">
				<div class="control-label">
					<label for="email">Post: </lable>
				</div>
				<div class="controls">
					<textarea></textarea>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input type="submit" class="btn btn-info" value="Post!"/>
				</div>
			<div>
		</form>
	</div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<% content_for :title do %>Edit Product<% end %>
<div class="hero-unit">
	<h3>Edit Product Details: </h3>
	<h3><%= @product.name %></h3>
</div>
<%= simple_form_for @product, :html => { :id => 'delete', :method => 'delete'} do |f| %>
	<%= f.button :submit, 'Delete Product', :class => 'btn-danger offset1' %>
<% end %>
<%= simple_form_for @product, :html => { :id => 'edit', :class => '.form-horizontal offset1'} do |f| %>
	<%= f.error_notification %>
	<%= f.input :name %>
	<%= f.input :description, :as => :string %>
	<%= f.input :pricing, :as => :string, :hint => 'USD only, please' %>
	<%= f.button :submit, :class => 'btn btn-info offset1' %>
<% end %>

app/views/products/index.html.erb
<% content_for :title do %>Product Listing<% end %>
<div class="hero-unit">
	<h3>Products</h3>
</div>
	<div class="well">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><h3><%= value %></h3></div>		
		<% end %>
		<table class="table table-striped table-bordered">
			<thead>
				<th>ID</td>
				<th>Product Name</th>
				<th>Product Description</th>
			</thead>
			<% @products.each do |product| %>
			<tr>
				<td><%= product.id %></td>
				<td><%= link_to(product.name, product_path(product.id) ) %></td>
				<td><%= product.description %></td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/products/new.html.erb
<%= content_for :title do %>Add a Product<% end %>
<div class="hero-unit">
	<h3>Add a Product</h3>
</div>
<%= simple_form_for @product, :html => {:id => 'product', :class => '.form-horizontal offset1'} do |f| %>
	<%= f.error_notification %>
	<%= f.association :category, :selected => 'category.name' %>
	<%= f.input :name %>
	<%= f.input :description, :as => :string %>
	<%= f.input :pricing, :as => :string %>
	<%= f.button :submit, :class => 'btn btn-info' %>
<% end %>

app/views/products/show.html.erb
<% content_for :title do %>Show Product<% end %>
<div class="hero-unit">
	<h3>Product: </h3>
	<h3><%= @products.name %></h3>	
</div>
<div class="well">
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><h3><%= value %></h3></div>		
	<% end %>
	<table class="table table-striped table-bordered">
		<thead>
			<th>ID</th>
			<th>Name</th>
			<th>Description</th>
			<th>Pricing</th>
			<th>Edit Product</th>
		</thead>
		<tr>
			<td><%= @products.id %></td>
			<td><%= @products.name %></td>
			<td><%= @products.description %></td>
			<td><%= @products.pricing %></td>
			<td><%= link_to( 'EDIT', edit_product_path(@products.id) ) %></td>
		</tr>
	</table>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/users/edit.html.erb
<% content_for :title do %>Edit user<% end %>
<div class="container">
<h1>Edit User Account Details</h1>

<%= simple_form_for @user, :html => { :id => 'delete', :method => 'delete'} do |f| %>
	<%= f.button :submit, 'Delete User', :class => 'btn-danger offset2' %>
<% end %>

<%= simple_form_for @user, :html => { :id => 'edit', :class => '.form-horizontal' } do |f| %>
	<%= f.error_notification %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email_address %>
	<%= f.input :password %>
	<%= f.button :submit %>
<% end %>

app/views/users/index.html.erb
<% content_for :title do %>Display All Users<% end %>

<div class="hero-unit">
	<h2>Welcome!</h2>
</div>
<div class="container">
	<div class="well">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><h3><%= value %></h3></div>		
		<% end %>
		<table class="table table-striped table-bordered">
			<thead><th>User Name</th></thead>
			<% @users.each do |user| %>
			<tr>
				<td><%= link_to(user.first_name + " " + user.last_name, user_path(user.id) )%></td><% end %>
			</tr>
		</table>
	</div>
</div>

app/views/users/new.html.erb
<% content_for :title do %>Add a new user<% end %>
<div class="container">
	<h1>Join the Crew</h1>
	<%= simple_form_for @user, :html => { :id => 'user', :class => '.form-horizontal' } do |f| %>
	<%= f.error_notification %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email_address %>
	<%= f.input :password %>
	<%= f.button :submit, :class => 'btn btn-info' %>
	<% end %>
</div>

app/views/users/show.html.erb
<% content_for :title do %>Display User<% end %>

<div class="hero-unit">
	<h2>User Details</h2>
</div>
<div class="container">
	<div class="well">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><h3><%= value %></h3></div>		
		<% end %>
		<table class="table table-striped table-bordered">
			<thead>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email</th>
				<th>Edit User</th>
			</thead>
			<tr>
				<td><%= @user.first_name %></td>
				<td><%= @user.last_name %></td>
				<td><%= @user.email_address %></td>
				<td><%= link_to( 'EDIT', edit_user_path(@user.id) ) %></td>
			</tr>
		</table>
	</div>
</div>